language: python
python:
  - 3.5

env:
  - PART=part1
  - PART=part2

install:
  - travis_retry pip install pytest pytest-cov coveralls

script:
  - cd $PART && py.test --cov .

after_script:
  - coveralls
